title: Joe Bartelmo
name: Joe Bartelmo
title_separator: "|"
email: joebartelmo@gmail.com
description: "Blog and personal development website. Home DIY, Computing Security, DevSecOps"
baseurl: ""
url: "http://joebartelmo.com"
github_username:  joebartelmo

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast" 
# "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Sass/SCSS
sass:
    style: compressed
permalink: /:categories/:title/
timezone: America/New_York
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

social:
    links:
        - "https://www.linkedin.com/in/joebartelmo"
include:
      - _pages
      - _posts
      - _computer_vision
      - _development
      - _security
      - _diy
author:
    name: "Joe Bartelmo"
    avatar: "/assets/images/me2.jpg"
    bio: "Blog and personal development website. Home DIY, Computing Security, DevSecOps"
    email: "joebartelmo@gmail.com"
    uri: "http://joebartelmo.com"
    linkedin: "joebartelmo"
    github: "joebartelmo"
    stackoverflow: "1938047/joe-bartelmo"
    bitbucket: "joebartelmo"

# Collections
collections:
  diy:
    output: true
    permalink: /:collection/:path/
  security:
    output: true
    permalink: /:collection/:path/
  computer_vision:
    output: true
    permalink: /:collection/:path/
  development:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: diy
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: security
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _computer_vision
  - scope:
      path: ""
      type: computer_vision
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _development
  - scope:
      path: ""
      type: development
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
envs: development
